// <auto-generated />
using System;
using EIA.S0.Infrastructure.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EIA.S0.Infrastructure.EntityFrameworkCore.PostgreSQL.Migrations
{
    [DbContext(typeof(EiaS0dbContext))]
    [Migration("20251126080539_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EIA.S0.Domain.Governance.Entities.DocType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AiDraftPromptTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_draft_prompt_template_id")
                        .HasComment("默认草稿 PromptTemplate Id");

                    b.PrimitiveCollection<string>("AllowedPhaseCodes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_phases")
                        .HasComment("允许的阶段编码集合");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id")
                        .HasComment("分类 Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code")
                        .HasComment("文档类型编码");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("创建时间");

                    b.Property<string>("CustomFieldsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_fields")
                        .HasComment("自定义字段");

                    b.Property<string>("DefaultPhaseCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("default_phase")
                        .HasComment("默认阶段编码");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasComment("描述");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasComment("元数据");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name")
                        .HasComment("名称");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("最后更新时间");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_doctype_category");

                    b.HasIndex("Code")
                        .HasDatabaseName("idx_doctype_code");

                    b.HasIndex("DefaultPhaseCode")
                        .HasDatabaseName("idx_doctype_defaultphase");

                    b.ToTable("doc_type", (string)null);
                });

            modelBuilder.Entity("EIA.S0.Domain.Governance.Entities.PhaseDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string>("AllowedTransitionPhaseCodes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_transitions")
                        .HasComment("允许跳转到的阶段编码集合");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("创建时间");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name")
                        .HasComment("显示名称");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("\"order\"")
                        .HasComment("顺序号");

                    b.Property<string>("PhaseCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("phase_code")
                        .HasComment("阶段编码");

                    b.Property<string>("PropertiesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties")
                        .HasComment("扩展属性");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("最后更新时间");

                    b.HasKey("Id");

                    b.HasIndex("Order")
                        .HasDatabaseName("idx_phase_definition_order");

                    b.HasIndex("PhaseCode")
                        .IsUnique()
                        .HasDatabaseName("ux_phase_definition_phase_code");

                    b.ToTable("phase_definition", (string)null);
                });

            modelBuilder.Entity("EIA.S0.Domain.IntegrationEventLogs.Aggregates.IntegrationEventLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("事件内容");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasComment("错误信息");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("事件名称");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("事件类型名称");

                    b.Property<string>("Identifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("事件标识");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("最后更新时间");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasComment("同一时间的顺序");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasComment("事件状态");

                    b.Property<int>("TimesSent")
                        .HasColumnType("integer")
                        .HasComment("发送次数");

                    b.HasKey("Id");

                    b.HasIndex("CreateTime", "State");

                    b.ToTable("IntegrationEventLog", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
