openapi: 3.0.3
info:
  title: S0 Governance - DocType API
  version: 1.0.0
paths:
  /api/governance/doctype:
    get:
      summary: Get DocType list
      operationId: listDocTypes
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
        - in: query
          name: size
          schema:
            type: integer
            minimum: 1
            maximum: 200
            default: 50
      responses:
        '200':
          description: DocType list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocType'
    post:
      summary: Create DocType
      operationId: createDocType
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDocTypeRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDocTypeResponse'
        '400':
          description: Validation error
  /api/governance/doctype/{id}:
    get:
      summary: Get DocType by id
      operationId: getDocType
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: DocType
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocType'
        '404':
          description: Not found
    put:
      summary: Update DocType
      operationId: updateDocType
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDocTypeRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateDocTypeResponse'
        '400':
          description: Validation error
        '404':
          description: Not found
    delete:
      summary: Delete DocType
      operationId: deleteDocType
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteDocTypeResponse'
        '404':
          description: Not found
components:
  schemas:
    DocType:
      type: object
      properties:
        id:
          type: string
          format: uuid
        code:
          type: string
        name:
          type: string
        description:
          type: string
          nullable: true
        allowedPhases:
          type: array
          items:
            type: string
        defaultPhase:
          type: string
        categoryId:
          type: string
          format: uuid
          nullable: true
        aiDraftPromptTemplateId:
          type: string
          format: uuid
          nullable: true
        metadata:
          type: object
          additionalProperties: true
          nullable: true
        customFields:
          type: object
          additionalProperties: true
          nullable: true
    CreateDocTypeRequest:
      type: object
      required:
        - code
        - name
        - allowedPhases
        - defaultPhase
      properties:
        code:
          type: string
        name:
          type: string
        description:
          type: string
          nullable: true
        allowedPhases:
          type: array
          items:
            type: string
        defaultPhase:
          type: string
        categoryId:
          type: string
          format: uuid
          nullable: true
        aiDraftPromptTemplateId:
          type: string
          format: uuid
          nullable: true
        metadata:
          type: object
          additionalProperties: true
          nullable: true
        customFields:
          type: object
          additionalProperties: true
          nullable: true
    CreateDocTypeResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
    UpdateDocTypeRequest:
      type: object
      required:
        - name
        - allowedPhases
        - defaultPhase
      properties:
        name:
          type: string
        description:
          type: string
          nullable: true
        allowedPhases:
          type: array
          items:
            type: string
        defaultPhase:
          type: string
        categoryId:
          type: string
          format: uuid
          nullable: true
        aiDraftPromptTemplateId:
          type: string
          format: uuid
          nullable: true
        metadata:
          type: object
          additionalProperties: true
          nullable: true
        customFields:
          type: object
          additionalProperties: true
          nullable: true
    UpdateDocTypeResponse:
      type: object
      properties:
        updated:
          type: boolean
    DeleteDocTypeResponse:
      type: object
      properties:
        deleted:
          type: boolean